### ISSUE TITLE
[1.15pre] hopper boats misbehaving

### ISSUE THREAD

**Issue by Yoghurt4C** [liachmodded/kayak#2]
hopper boats only accept one (1) itementity, and only in their first slot; if any more are thrown on top of the boat, the itementity is simply bounced off
examples:
-one full stack of any item thrown onto the boat - the entire stack gets sucked up, but anything other than it bounces off
-one stackable item thrown onto the boat - the single item gets sucked up, anything other than it bounces off
-one unstackable item thrown onto the boat - the single item gets sucked up, anything other than it bounces off

**Comment by liach** [comment]
so do stuff get suck up after hopper boats move? I expect the boat to only pick up one stack every 4 ticks when the boat is not moving. It should suck up more quickly when it is moving.

**Comment by Yoghurt4C** [comment]
https://files.catbox.moe/1cg4io.webm
